### ISSUE TITLE
[Discussion] Re-gain root access by backup repacking

### ISSUE THREAD

**Issue by antnks** [hack-technicolor/hack-technicolor#106]
Hi,

I have used one new way to get the root access back after an update. This looks more user friendly and does not require physical access to the device (for MITM attack). The only requirement: it will only work if you have had root access previously and saved the symmetric encryption key `/proc/rip/0108`

https://github.com/antnks/technicolor-config-decrypt

Please let me know if there is an interest and will prepare python proof of concept and prepare the documentation

**Comment by LuKePicci** [comment]
It is interesting for sure but it would be quite confusing to propose re-root strategies which works on the same device and firmware upon certain conditions. It's probably better if you start documenting stock backups repacking in general into Resources page. You can shortly mention this is a viable second-root strategy.

Did you give a look at this? https://github.com/Ansuel/Config-Crypt-Decrypt-Tch-Modem-Utility
AFAIK it is a little buggy on some firmwares since backups look like not being always encrypted the same way.

**Comment by antnks** [comment]
PR created: https://github.com/hack-technicolor/hack-technicolor/pull/120
