### ISSUE TITLE
TG389AC: bootloop during TFTP flashing

### ISSUE THREAD

**Issue by chaosdimension98** [hack-technicolor/hack-technicolor#303]
Hi peeps,

Re: Technicolor TG389AC MyRepublic WifiHub+

I encountered a failed firmware upgrade and now the router is bricked. When I tried to do a recovery using BOOTP and TFTP, it somehow keep on rebooting during the acknowledgement process for TFTP as illustrated below:

![image](https://github.com/hack-technicolor/hack-technicolor/assets/22585715/03971733-56b4-44a1-af2f-bb775f73da99)

Even wireshark shows it suddenly just jumps back to BOOTREQUEST again during acknowledgement.

![image](https://github.com/hack-technicolor/hack-technicolor/assets/22585715/191aa3af-c9e2-4901-97de-df2000efc25b)

Does anyone know what's wrong with it? Or what could be done?

Thank you

**Comment by wuseman** [comment]
It appears that during the TFTP firmware transfer process, the router is not acknowledging receipt of certain data blocks, resulting in a timeout. There could be several reasons for this issue:

Certainly! Let's break down the messages you provided step by step:

1. **Connection received from 192.168.1.101 on port 8192**:
    - The device (presumably your router) with the IP address `192.168.1.101` is establishing a connection to the TFTP server. The port `8192` indicates the port on which the device is sending the request.
    - **Potential Issues**: Network interruptions, device not correctly entering the recovery mode, or initial handshake problems.

2. **Read request for file <vbnt-l_16.3.7190-2761003-20170907085601-501361d1f0abcd3206e49f0897c4a6cca07a114d**:
    - The router is requesting the firmware file from the TFTP server.
    - **Potential Issues**: Wrong filename, corrupted firmware file, or wrong file path.

3. **TIMEOUT waiting for Ack block #3**:
    - TFTP (Trivial File Transfer Protocol) works by sending data in blocks and waiting for an acknowledgment (Ack) for each block before sending the next. In this case, the server sent block #3 but did not receive an acknowledgment from the router.
    - **Potential Issues**: Network interruptions, corrupted data blocks, firewall or security software interference, firmware incompatibility or corruption, or hardware issues.

4. **Rcvd BootP Msg for IP 0.0.0.0, Mac A4:91:B1:F4:F8:FC**:
    - The router is sending a BootP (Bootstrap Protocol) message, which is a precursor to DHCP. It's essentially asking for an IP address.
    - **Potential Issues**: The router might be rebooting itself during the TFTP process or facing issues which force it to restart the network stack.

5. **DHCP: proposed address 192.168.1.101**:
    - The DHCP server (which could be integrated into your TFTP server software or be a part of your network) is proposing an IP address (`192.168.1.101`) for the router.
    - **Potential Issues**: DHCP conflicts or IP address conflicts in the network. However, given the context, it seems to be a result of the router rebooting or resetting its network stack.

From the given logs, the main issue seems to be the timeout while waiting for the acknowledgment of block #3. This suggests either:

- **Network Issue**: Something is preventing the acknowledgment packet from reaching the TFTP server. This could be due to packet loss, cable issues, or interference.
  
- **Router Issue**: The router is not able to process the block or send an acknowledgment. This could be due to incompatible or corrupted firmware, hardware issues, or the router unexpectedly rebooting (as evidenced by the subsequent BootP message).

If the router consistently fails at block `#3`, it might be a firmware file issue or a specific hardware fault related to processing that particular data block.

**Comment by wuseman** [comment]
It appears that during the TFTP firmware transfer process, the router is not acknowledging receipt of certain data blocks, resulting in a timeout. There could be several reasons for this issue:

According to the tftp output, we can summary as this

1. **Connection received from 192.168.1.101 on port 8192**:
    - The device (presumably your router) with the IP address `192.168.1.101` is establishing a connection to the TFTP server. The port `8192` indicates the port on which the device is sending the request.
    - **Potential Issues**: Network interruptions, device not correctly entering the recovery mode, or initial handshake problems.

2. **Read request for file <vbnt-l_16.3.7190-2761003-20170907085601-501361d1f0abcd3206e49f0897c4a6cca07a114d**:
    - The router is requesting the firmware file from the TFTP server.
    - **Potential Issues**: Wrong filename, corrupted firmware file, or wrong file path.

3. **TIMEOUT waiting for Ack block #3**:
    - TFTP (Trivial File Transfer Protocol) works by sending data in blocks and waiting for an acknowledgment (Ack) for each block before sending the next. In this case, the server sent block #3 but did not receive an acknowledgment from the router.
    - **Potential Issues**: Network interruptions, corrupted data blocks, firewall or security software interference, firmware incompatibility or corruption, or hardware issues.

4. **Rcvd BootP Msg for IP 0.0.0.0, Mac A4:91:B1:F4:F8:FC**:
    - The router is sending a BootP (Bootstrap Protocol) message, which is a precursor to DHCP. It's essentially asking for an IP address.
    - **Potential Issues**: The router might be rebooting itself during the TFTP process or facing issues which force it to restart the network stack.

5. **DHCP: proposed address 192.168.1.101**:
    - The DHCP server (which could be integrated into your TFTP server software or be a part of your network) is proposing an IP address (`192.168.1.101`) for the router.
    - **Potential Issues**: DHCP conflicts or IP address conflicts in the network. However, given the context, it seems to be a result of the router rebooting or resetting its network stack.

From the given logs, the main issue seems to be the timeout while waiting for the acknowledgment of block #3. This suggests either:

- **Network Issue**: Something is preventing the acknowledgment packet from reaching the TFTP server. This could be due to packet loss, cable issues, or interference.
  
- **Router Issue**: The router is not able to process the block or send an acknowledgment. This could be due to incompatible or corrupted firmware, hardware issues, or the router unexpectedly rebooting (as evidenced by the subsequent BootP message).

If the router consistently fails at block `#3`, it might be a firmware file issue or a specific hardware fault related to processing that particular data block.

**Comment by chaosdimension98** [comment]
Hi wuseman,

Many thanks for the detailed explanation. For the moment, it seems like it would be a firmware file issue because the device I have is TG389AC HP like this:

![image](https://github.com/hack-technicolor/hack-technicolor/assets/22585715/11ba66d6-d5a2-4142-9587-14572ce89277)

I would try to get the RBI for GANT-2 firmware and see if it works before ruling it as hardware fault and throw away the bricked router.

Thanks again!

**Comment by wuseman** [comment]
Yes.. When you flash your router with the right firmware file, it will probably work.

You're welcome.

**Comment by chaosdimension98** [comment]
Unfortunately, seems like I couldn't find the firmware. Paper weight it is then! :)
